<?php
if(!defined('UPGRADING_PRGM') && !defined('INSTALLING_PRGM')) exit;

// fix up mainsettings
$DB->query("UPDATE {mainsettings} SET title = 'settings_website_url', description = 'settings_website_url_descr' WHERE `varname` = 'sdurl'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_enable_wysiwyg', description = 'settings_enable_wysiwyg_descr' WHERE `varname` = 'enablewysiwyg'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_admin_cookie_timeout', description = 'settings_admin_cookie_timeout_descr' WHERE `varname` = 'admincookietimeout'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_site_activation', description = 'settings_site_activation_descr' WHERE `varname` = 'siteactivation'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_off_reason', description = 'settings_off_reason_descr' WHERE `varname` = 'offmessage'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_website_title', description = 'settings_website_title_descr' WHERE `varname` = 'websitetitle'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_page_name_title', description = 'settings_page_name_title_descr' WHERE `varname` = 'categorytitle'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_page_name_title_position', description = 'settings_page_name_title_position_descr' WHERE `varname` = 'title_order'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_meta_keywords', description = 'settings_meta_keywords_descr' WHERE `varname` = 'metakeywords'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_page_title_separator', description = 'settings_page_title_separator_descr' WHERE `varname` = 'title_separator'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_meta_description', description = 'settings_meta_description_descr' WHERE `varname` = 'metadescription'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_seo_urls', description = 'settings_seo_urls_descr' WHERE `varname` = 'modrewrite'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_page_hierarchy_urls', description = 'settings_page_hierarchy_urls_descr' WHERE `varname` = 'url_subcategories'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_website_copyright', description = 'settings_website_copyright_descr' WHERE `varname` = 'copyrighttext'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_date_format', description = 'settings_date_format_descr' WHERE `varname` = 'dateformat'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_timezone_offset', description = 'settings_timezone_offset_descr' WHERE `varname` = 'timezoneoffset'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_daylight_savings', description = 'settings_daylight_savings_descr' WHERE `varname` = 'daylightsavings'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_charset', description = 'settings_charset_descr' WHERE `varname` = 'charset'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_db_charset', description = 'settings_db_charset_descr' WHERE `varname` = 'db_charset'");
$DB->query("UPDATE {mainsettings} SET title = 'settings_technical_email', description = 'settings_technical_email_descr' WHERE `varname` = 'technicalemail'");
$DB->query("UPDATE {mainsettings} SET `input` = 'yesno', `title` = 'comments_old_comments_first', `description` = 'comments_old_comments_first_descr', `value` = '1' WHERE `varname` = 'commentorder'");
$DB->query("DELETE FROM {mainsettings} WHERE varname = 'com_show_dates' LIMIT 1");

// fix up article settings
$DB->query("UPDATE {pluginsettings} SET groupname = 'article_display_settings' WHERE pluginid = 2");
$DB->query("UPDATE {pluginsettings} SET title = 'display_title', description = 'display_title_descr' WHERE description = 'Display Title' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_author', description = 'display_author_descr' WHERE description = 'Display Author' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_creation_date', description = 'display_creation_date_descr' WHERE description = 'Display Creation Date' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_updated_date', description = 'display_updated_date_descr' WHERE description = 'Display Updated Date' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_print_link', description = 'display_print_link_descr' WHERE description = 'Display Print Article Link' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_description_in_article', description = 'display_description_in_article_descr' WHERE description = 'Display Description Inside Article' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_comments', description = 'display_comments_descr' WHERE description = 'Display User Comments' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_on_main_page', description = 'display_on_main_page_descr' WHERE description = 'Display on main page listing' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'sticky_article', description = 'sticky_article_descr' WHERE description = 'Display as Sticky' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'title_link', description = 'title_link_descr' WHERE title = 'Title Link' AND pluginid = 2 LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'article_separator', description = 'article_separator_descr' WHERE title = 'News Article Separator' AND pluginid = 2 LIMIT 1");

// fix up latest article settings
$DB->query("UPDATE {pluginsettings} SET groupname = 'latest_articles_settings' WHERE pluginid = 3");
$DB->query("UPDATE {pluginsettings} SET title = 'display_limit', description = 'display_limit_descr' WHERE pluginid = 3 AND title = 'Limit' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'page_targeting', description = 'page_targeting_descr' WHERE pluginid = 3 AND title = 'Category Targeting' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'pages_to_include', description = 'pages_to_include_descr' WHERE pluginid = 3 AND title = 'Include Categories' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'sorting', description = 'sorting_descr' WHERE pluginid = 3 AND title = 'Sorting' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_page_name', description = 'display_page_name_descr' WHERE pluginid = 3 AND title = 'Display Category Name' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_description', description = 'display_description_descr' WHERE pluginid = 3 AND title = 'Display Description' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_read_more', description = 'display_read_more_descr' WHERE pluginid = 3 AND title = 'Read More' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_author', description = 'display_author_descr' WHERE pluginid = 3 AND title = 'Display Author' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_creation_date', description = 'display_creation_date_descr' WHERE pluginid = 3 AND title = 'Display Creation Date' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_updated_date', description = 'display_updated_date_descr' WHERE pluginid = 3 AND title = 'Display Updated Date' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'title_in_bold', description = 'title_in_bold_descr' WHERE pluginid = 3 AND title = 'Bold Title' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'title_link', description = 'title_link_descr' WHERE pluginid = 3 AND title = 'Title Link' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'page_link', description = 'page_link_descr' WHERE pluginid = 3 AND title = 'Category Link' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_pagination', description = 'display_pagination_descr' WHERE pluginid = 3 AND title = 'Display Pagination' LIMIT 1");

// fix up contact form settings
$DB->query("DELETE FROM {pluginsettings} where pluginid = 6 AND groupname = 'Attachment Options'");
$DB->query("UPDATE {pluginsettings} SET title = 'email_address', description = 'email_address_descr', groupname = 'contact_form_settings' WHERE pluginid = 6 AND title = 'Email' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'contact_form_paragraph', description = 'contact_form_paragraph_descr', groupname = 'contact_form_settings' WHERE pluginid = 6 AND title = 'Contact Form Title' LIMIT 1");

// fix up user login panel settings
$DB->query("UPDATE {pluginsettings} SET groupname = 'user_login_panel_settings' WHERE pluginid = 10");
$DB->query("UPDATE {pluginsettings} SET title = 'display_admin_link', description = 'display_admin_link_descr' WHERE pluginid = 10 AND title = 'Display Admin Link' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_profile_link', description = 'display_profile_link_descr' WHERE pluginid = 10 AND title = 'Display My Account Link' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_register_link', description = 'display_register_link_descr' WHERE pluginid = 10 AND title = 'Display Registration Link' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'display_forgot_password_link', description = 'display_forgot_password_link_descr' WHERE pluginid = 10 AND title = 'Display Forgot Password Link' LIMIT 1");

// fix up user profile settings
$DB->query("DELETE FROM {pluginsettings} where pluginid = 11");

// fix up user registration settings
$DB->query("UPDATE {pluginsettings} SET groupname = 'user_registration_settings' WHERE pluginid = 12");
$DB->query("UPDATE {pluginsettings} SET title = 'max_username_length', description = 'max_username_length_descr' WHERE pluginid = 12 AND title = 'Maximum Username Length' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'banned_emails', description = 'banned_emails_descr' WHERE pluginid = 12 AND title = 'Banned Email Addresses' LIMIT 1");
$DB->query("UPDATE {pluginsettings} SET title = 'require_email_activation', description = 'require_email_activation_descr' WHERE pluginid = 12 AND title = 'Require Email Activation' LIMIT 1");

// fix up image gallery settings
$DB->query("UPDATE {pluginsettings} SET groupname = 'image_gallery_settings' WHERE groupname = 'Options' AND pluginid = 17");
$DB->query("UPDATE {pluginsettings} SET title = 'image_display_mode', description = 'image_display_mode_desc' WHERE pluginid = 17 AND title = 'Image Display Mode'");
$DB->query("UPDATE {pluginsettings} SET title = 'images_per_row', description = 'images_per_row_desc' WHERE pluginid = 17 AND title = 'Number of images per Row'");
$DB->query("UPDATE {pluginsettings} SET title = 'images_per_page', description = 'images_per_page_desc' WHERE pluginid = 17 AND title = 'Images Per Page'");
$DB->query("UPDATE {pluginsettings} SET title = 'display_view_count', description = 'display_view_count_desc' WHERE pluginid = 17 AND title = 'Show View Counts'");
$DB->query("UPDATE {pluginsettings} SET title = 'display_author_name', description = 'display_author_name_desc' WHERE pluginid = 17 AND title = 'Show Submitted By'");
$DB->query("UPDATE {pluginsettings} SET title = 'center_images', description = 'center_images_desc' WHERE pluginid = 17 AND title = 'Center Images'");
$DB->query("UPDATE {pluginsettings} SET title = 'section_sort_order', description = 'section_sort_order_desc' WHERE pluginid = 17 AND title = 'Section Sort Order'");
$DB->query("UPDATE {pluginsettings} SET title = 'display_section_image_count', description = 'display_section_image_count_desc' WHERE pluginid = 17 AND title = 'Display Section Image Count'");
$DB->query("UPDATE {pluginsettings} SET title = 'section_images_per_row', description = 'section_images_per_row_desc' WHERE pluginid = 17 AND title = 'Number of Section Images per Row'");
$DB->query("UPDATE {pluginsettings} SET title = 'enable_comments', description = 'enable_comments_desc' WHERE pluginid = 17 AND title = 'Enable Comments'");

$DB->query("UPDATE {pluginsettings} SET groupname = 'midsize_settings' WHERE groupname = 'MidSize Options' AND pluginid = 17");
$DB->query("UPDATE {pluginsettings} SET title = 'create_midsize_images', description = 'create_midsize_images_desc' WHERE pluginid = 17 AND title = 'Create MidSize Images'");
$DB->query("UPDATE {pluginsettings} SET title = 'save_fullsize_images', description = 'save_fullsize_images_desc' WHERE pluginid = 17 AND title = 'Keep FullSize Images'");
$DB->query("UPDATE {pluginsettings} SET title = 'max_midsize_width', description = 'max_midsize_width_desc' WHERE pluginid = 17 AND title = 'Max MidSize Width'");
$DB->query("UPDATE {pluginsettings} SET title = 'max_midsize_height', description = 'max_midsize_height_desc' WHERE pluginid = 17 AND title = 'Max MidSize Height'");
$DB->query("UPDATE {pluginsettings} SET title = 'square_off_midsize', description = 'square_off_midsize_desc' WHERE pluginid = 17 AND title = 'Square Off MidSize'");

$DB->query("UPDATE {pluginsettings} SET groupname = 'thumbnail_settings' WHERE groupname = 'Thumbnail Options' AND pluginid = 17");
$DB->query("UPDATE {pluginsettings} SET title = 'auto_create_thumbs', description = 'auto_create_thumbs_desc' WHERE pluginid = 17 AND title = 'Image Resizing'");
$DB->query("UPDATE {pluginsettings} SET title = 'max_thumb_width', description = 'max_thumb_width_desc' WHERE pluginid = 17 AND title = 'Max Thumbnail Width'");
$DB->query("UPDATE {pluginsettings} SET title = 'max_thumb_height', description = 'max_thumb_height_desc' WHERE pluginid = 17 AND title = 'Max Thumbnail Height'");
$DB->query("UPDATE {pluginsettings} SET title = 'square_off_thumbs', description = 'square_off_thumbs_desc' WHERE pluginid = 17 AND title = 'Square off Thumbnails'");

$DB->query("UPDATE {pluginsettings} SET groupname = 'upload_settings' WHERE groupname = 'Upload Options' AND pluginid = 17");
$DB->query("UPDATE {pluginsettings} SET title = 'allowed_image_types', description = 'allowed_image_types_desc' WHERE pluginid = 17 AND title = 'Allowed Image Types'");
$DB->query("UPDATE {pluginsettings} SET title = 'max_upload_size', description = 'max_upload_size_desc' WHERE pluginid = 17 AND title = 'Max Image Upload Size'");
$DB->query("UPDATE {pluginsettings} SET title = 'image_notification', description = 'image_notification_desc' WHERE pluginid = 17 AND title = 'Image Notification'");
$DB->query("UPDATE {pluginsettings} SET title = 'auto_approve_images', description = 'auto_approve_images_desc' WHERE pluginid = 17 AND title = 'Auto Approve Images'");
$DB->query("UPDATE {pluginsettings} SET title = 'image_title_required', description = 'image_title_required_desc' WHERE pluginid = 17 AND title = 'Upload Requires Title'");
$DB->query("UPDATE {pluginsettings} SET title = 'image_description_required', description = 'image_description_required_desc' WHERE pluginid = 17 AND title = 'Upload Requires Description'");
$DB->query("UPDATE {pluginsettings} SET title = 'image_author_required', description = 'image_author_required_desc' WHERE pluginid = 17 AND title = 'Upload Requires Author'");
$DB->query("UPDATE {pluginsettings} SET title = 'allow_root_upload', description = 'allow_root_upload_desc' WHERE pluginid = 17 AND title = 'Allow Root Section Upload'");

$DB->query("INSERT INTO {adminphrases} (adminphraseid, adminpageid, pluginid, varname, defaultphrase) VALUES
(NULL, 0, 0, 'common_admin_panel', 'Admin Panel'),
(NULL, 0, 0, 'common_admin_theme_created_by', 'Admin Panel theme created by'),
(NULL, 0, 0, 'common_allow_administer', 'Allow Administer'),
(NULL, 0, 0, 'common_allow_download', 'Allow Download'),
(NULL, 0, 0, 'common_allow_submit', 'Allow Submit'),
(NULL, 0, 0, 'common_allow_view', 'Allow View'),
(NULL, 0, 0, 'common_click_to_redirect', 'Click here if you are not redirected.'),
(NULL, 0, 0, 'common_cloned_plugins', 'Cloned Plugins'),
(NULL, 0, 0, 'common_custom_plugins', 'Custom Plugins'),
(NULL, 0, 0, 'common_dashboard', 'Dashboard'),
(NULL, 0, 0, 'common_delete', 'Delete'),
(NULL, 0, 0, 'common_display_in_menu', 'Display page link in website Menu?'),
(NULL, 0, 0, 'common_downloaded_plugins', 'Downloaded Plugins'),
(NULL, 0, 0, 'common_login', 'Login'),
(NULL, 0, 0, 'common_logout', 'Logout'),
(NULL, 0, 0, 'common_main_plugins', 'Main Plugins'),
(NULL, 0, 0, 'common_no', 'No'),
(NULL, 0, 0, 'common_password', 'Password'),
(NULL, 0, 0, 'common_powered_by', 'Powered by'),
(NULL, 0, 0, 'common_setting_description', 'Setting Description'),
(NULL, 0, 0, 'common_setting_value', 'Setting Value'),
(NULL, 0, 0, 'common_skins', 'Skins'),
(NULL, 0, 0, 'common_update_settings', 'Update Settings'),
(NULL, 0, 0, 'common_usergroup', 'Usergroup'),
(NULL, 0, 0, 'common_username', 'Username'),
(NULL, 0, 0, 'common_view_site', 'View Site'),
(NULL, 0, 0, 'common_welcome', 'Welcome'),
(NULL, 0, 0, 'common_yes', 'Yes'),
(NULL, 0, 0, 'menu_articles', 'Articles'),
(NULL, 0, 0, 'menu_articles_page_settings', 'Page Article Settings'),
(NULL, 0, 0, 'menu_articles_search', 'Search for Articles'),
(NULL, 0, 0, 'menu_articles_settings', 'Article Settings'),
(NULL, 0, 0, 'menu_articles_view_articles', 'View Articles'),
(NULL, 0, 0, 'menu_articles_write_article', 'Write New Article'),
(NULL, 0, 0, 'menu_comments', 'Comments'),
(NULL, 0, 0, 'menu_comments_view_comment_settings', 'View Comment Settings'),
(NULL, 0, 0, 'menu_comments_view_comments', 'View Comments'),
(NULL, 0, 0, 'menu_comments_view_comments_by_plugin', 'View Comments by Plugin'),
(NULL, 0, 0, 'menu_media', 'Media'),
(NULL, 0, 0, 'menu_media_view_images', 'View Images'),
(NULL, 0, 0, 'menu_pages', 'Pages'),
(NULL, 0, 0, 'menu_pages_create_page', 'Create Page'),
(NULL, 0, 0, 'menu_pages_view_pages', 'View Pages'),
(NULL, 0, 0, 'menu_plugins', 'Plugins'),
(NULL, 0, 0, 'menu_plugins_create_custom_plugin', 'Create Custom Plugin'),
(NULL, 0, 0, 'menu_plugins_install_upgrade_plugins', 'Install & Upgrade Plugins'),
(NULL, 0, 0, 'menu_plugins_view_plugins', 'View Plugins'),
(NULL, 0, 0, 'menu_settings', 'Settings'),
(NULL, 0, 0, 'menu_settings_languages', 'Languages'),
(NULL, 0, 0, 'menu_settings_logo_settings', 'Website Logo'),
(NULL, 0, 0, 'menu_settings_main_settings', 'Main Settings'),
(NULL, 0, 0, 'menu_settings_seo_settings', 'SEO Settings'),
(NULL, 0, 0, 'menu_skins', 'Skins'),
(NULL, 0, 0, 'menu_skins_create_new_skin', 'Create New Skin'),
(NULL, 0, 0, 'menu_skins_import_skins', 'Import Skins'),
(NULL, 0, 0, 'menu_skins_view_all_skins', 'View all Skins'),
(NULL, 0, 0, 'menu_skins_view_current_skin', 'View Current Skin'),
(NULL, 0, 0, 'menu_users', 'Users'),
(NULL, 0, 0, 'menu_users_add_user', 'Add User'),
(NULL, 0, 0, 'menu_users_add_user_group', 'Add User Group'),
(NULL, 0, 0, 'menu_users_email_users', 'Email Users'),
(NULL, 0, 0, 'menu_users_search_users', 'Search Users'),
(NULL, 0, 0, 'menu_users_view_user_groups', 'View User Groups'),
(NULL, 0, 0, 'menu_users_view_users', 'View Users'),
(NULL, 1, 0, 'pages_caution', '<strong>Caution:</strong> the \"Set for all?\" option - if checked - will place the selected plugin (or \"Empty\") in ALL categories at that position with the same design being used.'),
(NULL, 1, 0, 'pages_confirm_delete_page', 'Delete page and any child pages?'),
(NULL, 1, 0, 'pages_create_page', 'Create Page'),
(NULL, 1, 0, 'pages_delete', 'Delete'),
(NULL, 1, 0, 'pages_delete_image', 'Delete Image'),
(NULL, 1, 0, 'pages_display_order', 'Display Order'),
(NULL, 1, 0, 'pages_error_common_plugins', 'You can not select the same plugin more than once per category.'),
(NULL, 1, 0, 'pages_error_folder_not_writable', 'Image upload failed, please chmod your \"images\" folder to 777.'),
(NULL, 1, 0, 'pages_error_invalid_file', 'Invalid file uploaded'),
(NULL, 1, 0, 'pages_error_invalid_page_name', 'Entered \"Page SEO Name\" is already being used by a different page, please choose another.'),
(NULL, 1, 0, 'pages_error_invalid_parent', 'Invalid parent selection.'),
(NULL, 1, 0, 'pages_external_link', 'External Link'),
(NULL, 1, 0, 'pages_external_link_target', 'External Link Target'),
(NULL, 1, 0, 'pages_layout', 'Layout'),
(NULL, 1, 0, 'pages_link_hover_image', 'Hover Image'),
(NULL, 1, 0, 'pages_link_image', 'Use Image in Place of Text'),
(NULL, 1, 0, 'pages_lost_pages_description', 'One or more of your pages are not being displayed above, this happens when an incorrect selection was made for a parent.<br /><br />List of lost pages:'),
(NULL, 1, 0, 'pages_lost_pages_found', 'Warning: Lost Pages Found'),
(NULL, 1, 0, 'pages_lost_pages_retrieved', 'Lost Pages Retrieved'),
(NULL, 1, 0, 'pages_meta_description', 'Meta Description'),
(NULL, 1, 0, 'pages_meta_keywords', 'Meta Keywords'),
(NULL, 1, 0, 'pages_name', 'Name'),
(NULL, 1, 0, 'pages_page_content', 'Page Content'),
(NULL, 1, 0, 'pages_page_deleted', 'Page Deleted'),
(NULL, 1, 0, 'pages_page_layout', 'Page Layout'),
(NULL, 1, 0, 'pages_page_link_settings', 'Page Link Settings'),
(NULL, 1, 0, 'pages_page_saved', 'Page Saved'),
(NULL, 1, 0, 'pages_page_settings', 'Page Settings'),
(NULL, 1, 0, 'pages_pages', 'Pages'),
(NULL, 1, 0, 'pages_pages_updated', 'Pages Updated'),
(NULL, 1, 0, 'pages_parent_page', 'Parent Page'),
(NULL, 1, 0, 'pages_permissions', 'Permissions'),
(NULL, 1, 0, 'pages_please_wait', 'Please wait'),
(NULL, 1, 0, 'pages_plugin_selection_description', 'Each plugin number in the page layout preview image corresponds with the plugin shown in it\'s selection box:'),
(NULL, 1, 0, 'pages_preview', 'Preview'),
(NULL, 1, 0, 'pages_retrieve_lost_pages', 'Retrieve Lost Pages'),
(NULL, 1, 0, 'pages_select_plugin', 'Select Plugin'),
(NULL, 1, 0, 'pages_select_plugin_layout', 'Select Page Layout:'),
(NULL, 1, 0, 'pages_seo_name', 'SEO Name'),
(NULL, 1, 0, 'pages_set_for_all', 'Set for all?'),
(NULL, 1, 0, 'pages_title', 'Title'),
(NULL, 1, 0, 'pages_update_page', 'Update Page'),
(NULL, 1, 0, 'pages_update_pages', 'Update Pages'),
(NULL, 1, 0, 'pages_usergroup_keyboard_instructions', 'Usergroups: <br /><br />(Use CTRL+click to de-/select single entries or SHIFT+click for multiple entries)'),
(NULL, 1, 0, 'pages_usergroup_link_instructions', 'Select which usergroups will see this page link in the website menu.'),
(NULL, 1, 0, 'pages_usergroup_none', 'None'),
(NULL, 1, 0, 'pages_usergroup_page_permissions', 'Usergroup Page Permissions'),
(NULL, 1, 0, 'pages_usergroup_permissions_updated', 'Page Permissions Updated'),
(NULL, 1, 0, 'pages_usergroup_update', 'Update Permissions'),
(NULL, 1, 0, 'pages_usergroup_view_instructions', 'Select which usergroups will be allowed to view this page.'),
(NULL, 1, 0, 'pages_view_page', 'View Page'),
(NULL, 2, 0, 'plugins_all_installed', 'All Plugins Installed'),
(NULL, 2, 0, 'plugins_all_up_to_date', 'All the plugins on your server have been installed and are up to date.'),
(NULL, 2, 0, 'plugins_author_name', 'Author Name'),
(NULL, 2, 0, 'plugins_create', 'Create'),
(NULL, 2, 0, 'plugins_custom_plugin', 'Custom Plugin'),
(NULL, 2, 0, 'plugins_custom_plugin_created', 'Custom Plugin Created'),
(NULL, 2, 0, 'plugins_custom_plugin_display_name', 'Custom Plugin Display Name'),
(NULL, 2, 0, 'plugins_custom_plugin_html', 'Custom Plugin HTML'),
(NULL, 2, 0, 'plugins_custom_plugin_include_file', 'Include File'),
(NULL, 2, 0, 'plugins_custom_plugin_include_file_description', 'File will be included after the custom plugin html. The file path has to be relative to the root directory. File type should be either PHP or HTML and should not have any spaces in the filename. For security reasons the file has to reside on the server\'s filesystem (no remote file inclusion).'),
(NULL, 2, 0, 'plugins_custom_plugin_name', 'Custom Plugin Name'),
(NULL, 2, 0, 'plugins_custom_plugin_updated', 'Custom Plugin Updated'),
(NULL, 2, 0, 'plugins_delete', 'Delete'),
(NULL, 2, 0, 'plugins_edit', 'Edit'),
(NULL, 2, 0, 'plugins_enter_custom_plugin_display_name', 'Enter the name that will be displayed on your website (for external display):'),
(NULL, 2, 0, 'plugins_enter_custom_plugin_name', 'Enter the name of this custom plugin (for internal use):'),
(NULL, 2, 0, 'plugins_failed_install', 'Could not install plugin. Failed opening'),
(NULL, 2, 0, 'plugins_install', 'Install'),
(NULL, 2, 0, 'plugins_install_upgrade_plugins', 'Install and Upgrade Plugins'),
(NULL, 2, 0, 'plugins_no_settings_found', 'This plugin does not have any settings.'),
(NULL, 2, 0, 'plugins_permissions', 'Permissions'),
(NULL, 2, 0, 'plugins_permissions_updated', 'Plugin Permissions Updated.'),
(NULL, 2, 0, 'plugins_plugin_display_names_updated', 'Plugin Display Names Updated'),
(NULL, 2, 0, 'plugins_plugin_id', 'Plugin ID'),
(NULL, 2, 0, 'plugins_plugin_installed', 'Plugin Installed'),
(NULL, 2, 0, 'plugins_plugin_name', 'Plugin Name'),
(NULL, 2, 0, 'plugins_plugin_not_found', 'Plugin not found.'),
(NULL, 2, 0, 'plugins_plugins', 'Plugins'),
(NULL, 2, 0, 'plugins_settings', 'Settings'),
(NULL, 2, 0, 'plugins_update', 'Update'),
(NULL, 2, 0, 'plugins_update_display_names', 'Update Plugin Display Names'),
(NULL, 2, 0, 'plugins_update_permissions', 'Update Permissions'),
(NULL, 2, 0, 'plugins_upgrade', 'Upgrade'),
(NULL, 2, 0, 'plugins_usergroup_permissions_for', 'Usergroup Permissions for Plugin'),
(NULL, 2, 0, 'plugins_version', 'Version'),
(NULL, 2, 0, 'plugins_website_display_name', 'Website Display Name'),
(NULL, 3, 0, 'media_browse_folder', 'Browse Folder'),
(NULL, 3, 0, 'media_cancel', 'Cancel'),
(NULL, 3, 0, 'media_click_thumb_for_full_image', 'Click the thumbnail to view the full sized image.'),
(NULL, 3, 0, 'media_could_not_open_folder', 'Could not open folder.'),
(NULL, 3, 0, 'media_create_thumb', 'Create Thumbnail'),
(NULL, 3, 0, 'media_create_thumbnail', 'Create Thumbnail'),
(NULL, 3, 0, 'media_delete', 'Delete'),
(NULL, 3, 0, 'media_delete_image', 'Delete Image'),
(NULL, 3, 0, 'media_delete_this_image', 'Do you wish to delete this image?'),
(NULL, 3, 0, 'media_enter_filename_for_thumb', 'Enter a filename for the thumbnail:'),
(NULL, 3, 0, 'media_enter_max_thumb_height', 'Enter the maximum pixels for the thumbnail\'s height:'),
(NULL, 3, 0, 'media_enter_max_thumb_width', 'Enter the maximum pixels for the thumbnail\'s width:'),
(NULL, 3, 0, 'media_image_deleted', 'Image Deleted'),
(NULL, 3, 0, 'media_image_details', 'Image Details'),
(NULL, 3, 0, 'media_image_not_deleted', 'Image could not be deleted'),
(NULL, 3, 0, 'media_image_uploaded', 'Image Uploaded'),
(NULL, 3, 0, 'media_images', 'Images'),
(NULL, 3, 0, 'media_invalid_image_extension', 'Invalid image file extention.'),
(NULL, 3, 0, 'media_invalid_image_name', 'Invalid image name.'),
(NULL, 3, 0, 'media_max_thumb_height', 'Max Thumbnail Height'),
(NULL, 3, 0, 'media_max_thumb_width', 'Max Thumbnail Width'),
(NULL, 3, 0, 'media_path', 'Path'),
(NULL, 3, 0, 'media_select_browse_folder', 'Select a folder to browse through:'),
(NULL, 3, 0, 'media_select_destination', 'Select Destination'),
(NULL, 3, 0, 'media_select_thumbnail_folder', 'Select the folder where you would like the thumbnail to be saved in:'),
(NULL, 3, 0, 'media_thumb_filename', 'Thumbnail Filename'),
(NULL, 3, 0, 'media_thumbnail_created', 'Thumbnail Created'),
(NULL, 3, 0, 'media_upload_error_0', 'Unknown File Error'),
(NULL, 3, 0, 'media_upload_error_1', 'The uploaded file exceeds the upload_max_filesize directive (2M) in php.ini.'),
(NULL, 3, 0, 'media_upload_error_2', 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form.'),
(NULL, 3, 0, 'media_upload_error_3', 'The uploaded file was only partially uploaded.'),
(NULL, 3, 0, 'media_upload_error_4', 'Missing a temporary folder.'),
(NULL, 3, 0, 'media_upload_error_5', 'Failed to write file to disk'),
(NULL, 3, 0, 'media_upload_error_6', 'File upload stopped by extension'),
(NULL, 3, 0, 'media_upload_error_invalid_image', 'Invalid image type.'),
(NULL, 3, 0, 'media_upload_error_no_image', 'No image uploaded or image size exceeds upload size limit.'),
(NULL, 3, 0, 'media_upload_error_not_writable', 'Could not move the image to folder, please make sure this folder is writable:'),
(NULL, 3, 0, 'media_upload_image', 'Upload Image'),
(NULL, 3, 0, 'media_upload_image_to_folder', 'Upload a new image to this folder:'),
(NULL, 4, 0, 'comments_approve_comment', 'Approve/Unapprove Comment:'),
(NULL, 4, 0, 'comments_approve_this_comment', 'Approve this comment?'),
(NULL, 4, 0, 'comments_approved', 'Approved'),
(NULL, 4, 0, 'comments_by_plugin', 'Comments by Plugin'),
(NULL, 4, 0, 'comments_comment', 'Comment:'),
(NULL, 4, 0, 'comments_comment_settings', 'Comment Settings'),
(NULL, 4, 0, 'comments_comment_updated', 'Comment Updated'),
(NULL, 4, 0, 'comments_comment2', 'Comment'),
(NULL, 4, 0, 'comments_comments_deleted', 'Comments Deleted'),
(NULL, 4, 0, 'comments_date', 'Date'),
(NULL, 4, 0, 'comments_delete', 'Delete'),
(NULL, 4, 0, 'comments_delete_comment', 'Delete Comment:'),
(NULL, 4, 0, 'comments_delete_comments', 'Delete Selected Comments'),
(NULL, 4, 0, 'comments_delete_this_comment', 'Delete this comment?'),
(NULL, 4, 0, 'comments_edit_comment', 'Edit Comment'),
(NULL, 4, 0, 'comments_item', 'Item:'),
(NULL, 4, 0, 'comments_latest_comments', 'Latest Comments'),
(NULL, 4, 0, 'comments_no', 'No'),
(NULL, 4, 0, 'comments_no_comments_found', 'No Comments Found'),
(NULL, 4, 0, 'comments_number_of_comments', 'Number of Comments'),
(NULL, 4, 0, 'comments_old_comments_first', 'Display Older Comments First'),
(NULL, 4, 0, 'comments_old_comments_first_descr', 'Display older comments first?<br />If you select \"No\", then comments will be sorted by new to old.'),
(NULL, 4, 0, 'comments_plugin', 'Plugin'),
(NULL, 4, 0, 'comments_plugin_item', 'Plugin Item'),
(NULL, 4, 0, 'comments_plugin_name', 'Plugin Name'),
(NULL, 4, 0, 'comments_settings_updated', 'Comment Settings Updated'),
(NULL, 4, 0, 'comments_update_comment', 'Update Comment'),
(NULL, 4, 0, 'comments_username', 'User Name:'),
(NULL, 4, 0, 'comments_username2', 'Username'),
(NULL, 4, 0, 'comments_yes', 'Yes'),
(NULL, 5, 0, 'users_account_status', 'Account Status'),
(NULL, 5, 0, 'users_activated', 'Activated'),
(NULL, 5, 0, 'users_activation_link_sent', 'Activation link sent.'),
(NULL, 5, 0, 'users_add_user', 'Add User'),
(NULL, 5, 0, 'users_admin_notes', 'Admin Notes'),
(NULL, 5, 0, 'users_admin_notes_text', 'These notes are not visible to the user.'),
(NULL, 5, 0, 'users_allow_administer', 'Allow Administer'),
(NULL, 5, 0, 'users_allow_download', 'Allow Download'),
(NULL, 5, 0, 'users_allow_submit', 'Allow Submit'),
(NULL, 5, 0, 'users_allow_view', 'Allow View'),
(NULL, 5, 0, 'users_can_not_delete_self', 'You can not delete yourself!'),
(NULL, 5, 0, 'users_comment_access', 'Comment Access'),
(NULL, 5, 0, 'users_comment_access_descr', 'Allow users to post comments?'),
(NULL, 5, 0, 'users_confirm_delete_usergroup', 'Are you sure you wish to delete this usergroup?'),
(NULL, 5, 0, 'users_create_usergroup', 'Create User Group'),
(NULL, 5, 0, 'users_delete', 'Delete'),
(NULL, 5, 0, 'users_edit_user', 'Edit User'),
(NULL, 5, 0, 'users_edit_usergroup', 'Edit User Group'),
(NULL, 5, 0, 'users_email', 'Email'),
(NULL, 5, 0, 'users_email_click_to_unsubscribe', 'Click here to unsubscribe.'),
(NULL, 5, 0, 'users_email_content_type', 'Content Type:'),
(NULL, 5, 0, 'users_email_emailing_users', 'Emailing Users'),
(NULL, 5, 0, 'users_email_emails_remaining', 'emails remaining'),
(NULL, 5, 0, 'users_email_emails_sent', 'email(s) sent successfully.'),
(NULL, 5, 0, 'users_email_from_address', 'From Address:'),
(NULL, 5, 0, 'users_email_from_address_missing', 'Please enter an email address in the \"From Address\" field.'),
(NULL, 5, 0, 'users_email_from_name', 'From Name:'),
(NULL, 5, 0, 'users_email_from_name_missing', 'Please enter a name in the \"From Name\" field.'),
(NULL, 5, 0, 'users_email_html', 'HTML'),
(NULL, 5, 0, 'users_email_message', 'Message:'),
(NULL, 5, 0, 'users_email_message_missing', 'Please enter in the email message.'),
(NULL, 5, 0, 'users_email_nobody_to_email', 'Could not find anyone to email.'),
(NULL, 5, 0, 'users_email_send', 'Send'),
(NULL, 5, 0, 'users_email_send_to_user_groups', 'Send to User Groups:<br />(Use CTRL+click to de-/select single entries)'),
(NULL, 5, 0, 'users_email_sending_emails', 'Sending emails, please wait...'),
(NULL, 5, 0, 'users_email_sent_to', 'Email sent to:'),
(NULL, 5, 0, 'users_email_subject', 'Subject:'),
(NULL, 5, 0, 'users_email_subject_and_message', 'Subject and Message'),
(NULL, 5, 0, 'users_email_subject_missing', 'Please enter in the email subject.'),
(NULL, 5, 0, 'users_email_text', 'Text'),
(NULL, 5, 0, 'users_email_to_address', 'To Address:<br />(separate multiple addresses with a comma)'),
(NULL, 5, 0, 'users_email_to_and_from', 'To and From'),
(NULL, 5, 0, 'users_email_visit_to_unsubscribe', 'Visit this link to unsubscribe:'),
(NULL, 5, 0, 'users_enter_email', 'Please enter an email address.'),
(NULL, 5, 0, 'users_enter_password', 'Please enter a password.'),
(NULL, 5, 0, 'users_enter_username', 'Please enter a username.'),
(NULL, 5, 0, 'users_full_admin', 'Full Admin Access'),
(NULL, 5, 0, 'users_full_admin_descr', 'Enabling this setting will give users in this user group full access to the administration panel.'),
(NULL, 5, 0, 'users_join_date', 'Join Date'),
(NULL, 5, 0, 'users_last_activity_date', 'Last Activity Date'),
(NULL, 5, 0, 'users_missing_users_plugin', 'The \"User Registration\" plugin must be present in a category before continuing.'),
(NULL, 5, 0, 'users_not_activated', 'Not Activated'),
(NULL, 5, 0, 'users_offline_access', 'Offline Access'),
(NULL, 5, 0, 'users_offline_access_descr', 'Users in this user group will be able to view your website in offline mode and also view any offline categories.'),
(NULL, 5, 0, 'users_page_name', 'Page Name'),
(NULL, 5, 0, 'users_page_permissions', 'Page Permissions'),
(NULL, 5, 0, 'users_password', 'Password'),
(NULL, 5, 0, 'users_plugin_permissions', 'Plugin Permissions'),
(NULL, 5, 0, 'users_search_all', 'Search All'),
(NULL, 5, 0, 'users_search_users', 'Search Users'),
(NULL, 5, 0, 'users_send_activation_link_failed', 'Failed to send activation link email.'),
(NULL, 5, 0, 'users_status', 'Status'),
(NULL, 5, 0, 'users_update_user', 'Update User'),
(NULL, 5, 0, 'users_update_usergroup', 'Update User Group'),
(NULL, 5, 0, 'users_user_count', 'User Count'),
(NULL, 5, 0, 'users_user_deleted', 'User Deleted'),
(NULL, 5, 0, 'users_user_inserted', 'User Inserted'),
(NULL, 5, 0, 'users_user_not_found', 'User not found.'),
(NULL, 5, 0, 'users_user_updated', 'User Updated'),
(NULL, 5, 0, 'users_usergroup', 'User Group'),
(NULL, 5, 0, 'users_usergroup_created', 'User Group Created'),
(NULL, 5, 0, 'users_usergroup_deleted', 'User Group Deleted'),
(NULL, 5, 0, 'users_usergroup_name', 'User Group Name'),
(NULL, 5, 0, 'users_usergroup_name_descr', 'Name this usergroup.'),
(NULL, 5, 0, 'users_usergroup_updated', 'User Group Updated'),
(NULL, 5, 0, 'users_usergroups', 'User Groups'),
(NULL, 5, 0, 'users_username', 'Username'),
(NULL, 5, 0, 'users_users', 'Users'),
(NULL, 5, 0, 'users_validating', 'Validating'),
(NULL, 5, 0, 'users_validating_link', 'Send user an email with activation link'),
(NULL, 5, 0, 'users_view_user', 'View User'),
(NULL, 5, 0, 'users_view_usergroup', 'View User Group'),
(NULL, 6, 0, 'skins_all_installed', 'All Skins Installed'),
(NULL, 6, 0, 'skins_author_information', 'Author Information'),
(NULL, 6, 0, 'skins_author_link', 'Author Website Link:'),
(NULL, 6, 0, 'skins_author_name', 'Author Name:'),
(NULL, 6, 0, 'skins_body_start_tag', 'Starting Body Tag'),
(NULL, 6, 0, 'skins_click_to_switch', 'Click here to switch to this skin'),
(NULL, 6, 0, 'skins_clone_skin', 'Create skin HTML and CSS code based off an existing skin:'),
(NULL, 6, 0, 'skins_confirm_uninstall', 'Are you sure you want to uninstall this skin?'),
(NULL, 6, 0, 'skins_create_new_layout', 'Create New Layout'),
(NULL, 6, 0, 'skins_create_skin', 'Create Skin'),
(NULL, 6, 0, 'skins_css', 'CSS'),
(NULL, 6, 0, 'skins_current', 'Current Skin'),
(NULL, 6, 0, 'skins_details', 'Skin Details'),
(NULL, 6, 0, 'skins_edit_details', 'Edit Skin Details'),
(NULL, 6, 0, 'skins_enter_full_xml_filepath', 'Please enter the full path to the xml file.'),
(NULL, 6, 0, 'skins_error_page', 'Error Page'),
(NULL, 6, 0, 'skins_export_skin', 'Export Skin'),
(NULL, 6, 0, 'skins_footer', 'Footer'),
(NULL, 6, 0, 'skins_head_include', 'Head Include'),
(NULL, 6, 0, 'skins_header', 'Header'),
(NULL, 6, 0, 'skins_html_doctype', 'HTML Doctype'),
(NULL, 6, 0, 'skins_html_start_tag', 'Starting HTML Tag'),
(NULL, 6, 0, 'skins_import_path', 'Skin XML file path:<br />(example: my_skin/skin.xml)'),
(NULL, 6, 0, 'skins_import_skin', 'Import Skin'),
(NULL, 6, 0, 'skins_install_old_skin', 'Install Last Generation Skins'),
(NULL, 6, 0, 'skins_install_skin', 'Install Skin'),
(NULL, 6, 0, 'skins_layout', 'Layout'),
(NULL, 6, 0, 'skins_name', 'Skin Name'),
(NULL, 6, 0, 'skins_none', 'None'),
(NULL, 6, 0, 'skins_old_engine_notice', 'Your current skin is using the old skin engine, you will only be able to edit the system\'s CSS code.'),
(NULL, 6, 0, 'skins_plugin_positions', 'Plugin Positions'),
(NULL, 6, 0, 'skins_plugins_delete', 'Delete all Plugin Positions'),
(NULL, 6, 0, 'skins_plugins_delete_descr', 'This option will delete all current plugin positions, your website will be empty. You will need to select the positions of plugins for every page.'),
(NULL, 6, 0, 'skins_plugins_keep', 'Keep Current Plugin Positions'),
(NULL, 6, 0, 'skins_plugins_keep_descr', 'Selecting this option will speed up the transition of switching to a new skin by maintaining the current positions of all plugins. However, you may need to re-arrange the plugin positions due to the diverse layouts of each skin.'),
(NULL, 6, 0, 'skins_plugins_restore', 'Restore Plugin Positions from Backup'),
(NULL, 6, 0, 'skins_plugins_restore_descr', 'If you have used this skin before, then this option will restore the plugin positions that were previously used.'),
(NULL, 6, 0, 'skins_preview', 'Preview'),
(NULL, 6, 0, 'skins_select_structure', 'Select Structure'),
(NULL, 6, 0, 'skins_select_xml_file', 'Select the XML file to export your skin to'),
(NULL, 6, 0, 'skins_select_xml_file_descr', 'Use the export function if you need to backup your skin.<br />Exporting your skin will backup all of the skins\'s HTML and CSS code to the specified XML file.'),
(NULL, 6, 0, 'skins_settings', 'Skin Settings'),
(NULL, 6, 0, 'skins_skin_created', 'Skin Created'),
(NULL, 6, 0, 'skins_skin_exported', 'Skin has been successfully exported.'),
(NULL, 6, 0, 'skins_skin_folder', 'Skin Folder:<br />(the folder where skin images will be saved, optional)'),
(NULL, 6, 0, 'skins_skin_imported', 'Skin Imported'),
(NULL, 6, 0, 'skins_skin_installed', 'Skin Installed'),
(NULL, 6, 0, 'skins_skin_name', 'Skin Name:'),
(NULL, 6, 0, 'skins_skin_switched', 'Skin Switched'),
(NULL, 6, 0, 'skins_skin_uninstalled', 'Skin Uninstalled'),
(NULL, 6, 0, 'skins_skin_updated', 'Skin Updated'),
(NULL, 6, 0, 'skins_structure', 'Skin Structure'),
(NULL, 6, 0, 'skins_switch_descr', 'When switching to a new skin you must decide what should happen with the current layout of your plugins:'),
(NULL, 6, 0, 'skins_switch_skin', 'Switch Skin'),
(NULL, 6, 0, 'skins_switch_to_skin', 'Switch to this skin'),
(NULL, 6, 0, 'skins_switching_to', 'Switching to'),
(NULL, 6, 0, 'skins_title_setting', 'Title is set under Settings'),
(NULL, 6, 0, 'skins_update_skin', 'Update Skin'),
(NULL, 6, 0, 'skins_visit_author_site', 'Visit Author\'s Website'),
(NULL, 6, 0, 'skins_xml_file_not_found', 'Could not find file'),
(NULL, 6, 0, 'skins_xml_file_not_writable', 'XML file is not writable, please temporarily CHMOD it to 666.'),
(NULL, 7, 0, 'settings_admin_cookie_timeout', 'Admin Timeout'),
(NULL, 7, 0, 'settings_admin_cookie_timeout_descr', 'Number of seconds of idle time before you are automatically logged out of the admin control panel (default 900 = 15 minutes)<br />Entering a value of 0 here will mean that you session will never timeout:'),
(NULL, 7, 0, 'settings_admin_language', 'Admin Panel Language'),
(NULL, 7, 0, 'settings_admin_pages', 'Admin Pages'),
(NULL, 7, 0, 'settings_character_encoding', 'Character Encoding'),
(NULL, 7, 0, 'settings_charset', 'Character Set'),
(NULL, 7, 0, 'settings_charset_descr', 'Enter the character set of your website:<br />Default is UTF-8'),
(NULL, 7, 0, 'settings_common_phrases', 'Common Phrases'),
(NULL, 7, 0, 'settings_custom_phrase', 'Custom Phrase'),
(NULL, 7, 0, 'settings_date_format', 'Date Format'),
(NULL, 7, 0, 'settings_date_format_descr', 'Format in which the date is presented:<br />Visit http://us2.php.net/manual/en/function.date.php for more information.'),
(NULL, 7, 0, 'settings_date_time_settings', 'Date and Time Settings'),
(NULL, 7, 0, 'settings_daylight_savings', 'Enable Daylight Savings'),
(NULL, 7, 0, 'settings_daylight_savings_descr', 'If Daylight Savings Time is currently in effect for the above time zone, enable this option so that guests will see the correct times'),
(NULL, 7, 0, 'settings_db_charset', 'Database Character Set'),
(NULL, 7, 0, 'settings_db_charset_descr', 'Enter the character set of your database:<br />This should be the same as your character set, default is UTF-8.'),
(NULL, 7, 0, 'settings_default_phrase', 'Default Phrase'),
(NULL, 7, 0, 'settings_email_settings', 'Email Settings'),
(NULL, 7, 0, 'settings_enable_wysiwyg', 'Enable WYSIWYG Editor'),
(NULL, 7, 0, 'settings_enable_wysiwyg_descr', 'Enable the WYSIWYG editor in the admin panel?'),
(NULL, 7, 0, 'settings_export_language', 'Export Language'),
(NULL, 7, 0, 'settings_general_settings', 'General Settings'),
(NULL, 7, 0, 'settings_language_author', 'Author:'),
(NULL, 7, 0, 'settings_language_author_descr', 'You can leave your name in the language file if you enter it here:'),
(NULL, 7, 0, 'settings_language_name', 'Name:'),
(NULL, 7, 0, 'settings_language_name_descr', 'Enter the name of the language:'),
(NULL, 7, 0, 'settings_language_switched', 'Language Switched'),
(NULL, 7, 0, 'settings_language_version', 'Version'),
(NULL, 7, 0, 'settings_language_version_descr', 'Enter the version number of this language file:'),
(NULL, 7, 0, 'settings_main_phrases', 'Main Website Phrases'),
(NULL, 7, 0, 'settings_meta_description', 'Meta Description'),
(NULL, 7, 0, 'settings_meta_description_descr', 'Description of your website: <br />Helps your website\'s position in search engines.'),
(NULL, 7, 0, 'settings_meta_keywords', 'Meta Keywords'),
(NULL, 7, 0, 'settings_meta_keywords_descr', 'Type in keywords separated by commas that describe your website. <br />These keywords will help your site be listed in search engines:'),
(NULL, 7, 0, 'settings_off_reason', 'Off Reason'),
(NULL, 7, 0, 'settings_off_reason_descr', 'You may provide a short description to your members explaining why your site has been switched off:'),
(NULL, 7, 0, 'settings_page_hierarchy_urls', 'Display Page Hierarchy in URLs'),
(NULL, 7, 0, 'settings_page_hierarchy_urls_descr', 'If set to Yes, URL\'s will display the page hierarchy.'),
(NULL, 7, 0, 'settings_page_name_title', 'Combine Page Name with Title Tag'),
(NULL, 7, 0, 'settings_page_name_title_descr', 'By selecting this option, the name of the displayed page will be added to your website\'s title.'),
(NULL, 7, 0, 'settings_page_name_title_position', 'Page Name and Title Tag Positions'),
(NULL, 7, 0, 'settings_page_name_title_position_descr', 'If page names are to be displayed in the page title tags, then select their position:'),
(NULL, 7, 0, 'settings_page_title_separator', 'Page Name and Website Title Separator'),
(NULL, 7, 0, 'settings_page_title_separator_descr', 'Enter a character that separates the website title and page name.'),
(NULL, 7, 0, 'settings_phrases', 'Phrases'),
(NULL, 7, 0, 'settings_phrases_edited', 'Phrases Edited'),
(NULL, 7, 0, 'settings_select_language', 'Select your Language'),
(NULL, 7, 0, 'settings_select_language_descr', 'Select which language you would like to switch to:'),
(NULL, 7, 0, 'settings_seo_settings', 'SEO Settings'),
(NULL, 7, 0, 'settings_seo_urls', 'SEO URLs'),
(NULL, 7, 0, 'settings_seo_urls_descr', 'If your server is running off of apache and has Mod Rewrite enabled, then you can turn this setting on to make your URLs more user friendly:'),
(NULL, 7, 0, 'settings_site_activation', 'Turn Site On/Off'),
(NULL, 7, 0, 'settings_site_activation_descr', 'You may want to turn off your site while performing updates or other types of maintenance.'),
(NULL, 7, 0, 'settings_switch_language', 'Switch Language'),
(NULL, 7, 0, 'settings_technical_email', 'Technical Email'),
(NULL, 7, 0, 'settings_technical_email_descr', 'Any errors or problems will be mailed to this address:<br />Leave blank if you do not wish to receive technical emails.<br />Separate multiple addresses with commas.'),
(NULL, 7, 0, 'settings_timezone_offset', 'Default Time Zone Offset'),
(NULL, 7, 0, 'settings_timezone_offset_descr', 'Time zone offset for guests and new users. Do not take DST into consideration, rather use the next option to enable/disable DST.'),
(NULL, 7, 0, 'settings_update_phrases', 'Update Phrases'),
(NULL, 7, 0, 'settings_updated', 'Settings Updated'),
(NULL, 7, 0, 'settings_website_copyright', 'Website Copyright'),
(NULL, 7, 0, 'settings_website_copyright_descr', 'Enter your copyright information here:'),
(NULL, 7, 0, 'settings_website_language', 'Website Language'),
(NULL, 7, 0, 'settings_website_logo', 'Website Logo'),
(NULL, 7, 0, 'settings_website_title', 'Website Title'),
(NULL, 7, 0, 'settings_website_title_descr', 'Name your website:'),
(NULL, 7, 0, 'settings_website_url', 'Website URL'),
(NULL, 7, 0, 'settings_website_url_descr', 'Please enter the full URL to your website:<br />This setting is required in order for your site to function correctly.'),
(NULL, 2, 2, 'article', 'Article'),
(NULL, 2, 2, 'article_created', 'Article Created'),
(NULL, 2, 2, 'article_description', 'Article Description'),
(NULL, 2, 2, 'article_details', 'Article Details'),
(NULL, 2, 2, 'article_display_settings', 'Article Display Settings'),
(NULL, 2, 2, 'article_separator', 'Article Separator'),
(NULL, 2, 2, 'article_separator_descr', 'How would you like the articles to be separated?<br />You can enter HTML tags here.'),
(NULL, 2, 2, 'article_sorting_method', 'Article Sorting Method'),
(NULL, 2, 2, 'article_title_az', 'Article Title A-Z'),
(NULL, 2, 2, 'article_title_za', 'Article Title Z-A'),
(NULL, 2, 2, 'article_updated', 'Article Updated'),
(NULL, 2, 2, 'articles', 'Articles'),
(NULL, 2, 2, 'articles_deleted', 'Articles Deleted'),
(NULL, 2, 2, 'articles_updated', 'Articles Updated'),
(NULL, 2, 2, 'author', 'Author'),
(NULL, 2, 2, 'author_name_az', 'Author Name A-Z'),
(NULL, 2, 2, 'author_name_za', 'Author Name Z-A'),
(NULL, 2, 2, 'date_created', 'Date Created'),
(NULL, 2, 2, 'date_updated', 'Date Updated'),
(NULL, 2, 2, 'delete', 'Delete'),
(NULL, 2, 2, 'delete_the_following_articles', 'Delete the following articles?'),
(NULL, 2, 2, 'display_author', 'Display Author'),
(NULL, 2, 2, 'display_author_descr', 'Display the author\'s name?'),
(NULL, 2, 2, 'display_comments', 'Display User Comments'),
(NULL, 2, 2, 'display_comments_descr', 'Display user comments after each article?'),
(NULL, 2, 2, 'display_creation_date', 'Display Creation Date'),
(NULL, 2, 2, 'display_creation_date_descr', 'Display the article\'s creation date?'),
(NULL, 2, 2, 'display_description_in_article', 'Display Description Inside Article'),
(NULL, 2, 2, 'display_description_in_article_descr', 'Would you like the article\'s description to be displayed when viewing the full article?'),
(NULL, 2, 2, 'display_multiple_pages_of_articles', 'Display Multiple Pages of Articles'),
(NULL, 2, 2, 'display_on_common_page', 'Display Article on main page'),
(NULL, 2, 2, 'display_on_main_page', 'Display Article on main page'),
(NULL, 2, 2, 'display_on_main_page_descr', 'If you select \"No\", then articles will be hidden from your website.'),
(NULL, 2, 2, 'display_order', 'Display Order'),
(NULL, 2, 2, 'display_order_asc', 'Display Order Asc'),
(NULL, 2, 2, 'display_order_descr', 'Display Order Desc'),
(NULL, 2, 2, 'display_print_link', 'Display Print Article Link'),
(NULL, 2, 2, 'display_print_link_descr', 'Display the \"Print Article\" link?'),
(NULL, 2, 2, 'display_title', 'Display Title'),
(NULL, 2, 2, 'display_title_descr', 'Display the title of the article?'),
(NULL, 2, 2, 'display_updated_date', 'Display Updated Date'),
(NULL, 2, 2, 'display_updated_date_descr', 'Display the date of when the article was last updated?'),
(NULL, 2, 2, 'edit_description', 'Edit Description'),
(NULL, 2, 2, 'end_publishing', 'End Publishing'),
(NULL, 2, 2, 'enter_search_terms', 'Enter in your search terms:'),
(NULL, 2, 2, 'insert_article', 'Submit Article'),
(NULL, 2, 2, 'max_articles_per_page', 'Max Articles Per Page'),
(NULL, 2, 2, 'meta_description', 'Meta Description'),
(NULL, 2, 2, 'meta_keywords', 'Meta Keywords'),
(NULL, 2, 2, 'newest_first', 'Newest First'),
(NULL, 2, 2, 'no', 'No'),
(NULL, 2, 2, 'no_articles_exist', 'No articles exist, click on \"Write New Article\" to get started.'),
(NULL, 2, 2, 'no_articles_found', 'No articles found.'),
(NULL, 2, 2, 'offline', 'Offline'),
(NULL, 2, 2, 'oldest_first', 'Oldest First'),
(NULL, 2, 2, 'online', 'Online'),
(NULL, 2, 2, 'page', 'Page'),
(NULL, 2, 2, 'page_article_settings', 'Page Article Settings'),
(NULL, 2, 2, 'page_name', 'Page Name'),
(NULL, 2, 2, 'pagebreak_description', 'Separate multiple pages with {pagebreak}'),
(NULL, 2, 2, 'publish_date', 'Publish Date'),
(NULL, 2, 2, 'search', 'Search'),
(NULL, 2, 2, 'search_articles', 'Search Articles'),
(NULL, 2, 2, 'seo_title', 'SEO Title'),
(NULL, 2, 2, 'settings', 'Settings'),
(NULL, 2, 2, 'settings_updated', 'Settings Updated'),
(NULL, 2, 2, 'sort_by', 'Sort by'),
(NULL, 2, 2, 'start_publishing', 'Start Publishing'),
(NULL, 2, 2, 'status', 'Status'),
(NULL, 2, 2, 'sticky_article', 'Sticky Article'),
(NULL, 2, 2, 'sticky_article_descr', 'Sticky articles remain stuck on your website, you should disable this option.'),
(NULL, 2, 2, 'title', 'Title'),
(NULL, 2, 2, 'title_link', 'Title Link'),
(NULL, 2, 2, 'title_link_descr', 'Would you like the article\'s title to link to the full article?'),
(NULL, 2, 2, 'update_article', 'Update Article'),
(NULL, 2, 2, 'update_articles', 'Update Articles'),
(NULL, 2, 2, 'use_global_settings', 'Use Global Settings'),
(NULL, 2, 2, 'views', 'Views'),
(NULL, 2, 2, 'yes', 'Yes'),
(NULL, 2, 3, 'display_creation_date', 'Display Creation Date'),
(NULL, 2, 3, 'display_creation_date_descr', 'Display the article\'s creation date?'),
(NULL, 2, 3, 'display_description', 'Display Description'),
(NULL, 2, 3, 'display_description_descr', 'Display article descriptions?'),
(NULL, 2, 3, 'display_limit', 'Display Limit'),
(NULL, 2, 3, 'display_limit_descr', 'Maximum number of article links to display per page:'),
(NULL, 2, 3, 'display_page_name', 'Display Page Name'),
(NULL, 2, 3, 'display_page_name_descr', 'Display the page name near the article\'s title?'),
(NULL, 2, 3, 'display_pagination', 'Display Pagination'),
(NULL, 2, 3, 'display_pagination_descr', 'Display pagination for multiple pages?'),
(NULL, 2, 3, 'display_read_more', 'Display Read More'),
(NULL, 2, 3, 'display_read_more_descr', 'Display the \"Read More\" link? This might be useful if you are enabling the display of descriptions.'),
(NULL, 2, 3, 'display_updated_date', 'Display Updated Date'),
(NULL, 2, 3, 'display_updated_date_descr', 'Display the date of when the article was last updated?'),
(NULL, 2, 3, 'latest_articles_settings', 'Latest Articles Settings'),
(NULL, 2, 3, 'page_link', 'Page Link'),
(NULL, 2, 3, 'page_link_descr', 'If you are enabling \"Display Page Name\", then you can enable this setting to turn that name into a link.'),
(NULL, 2, 3, 'page_targeting', 'Page Targeting'),
(NULL, 2, 3, 'page_targeting_descr', 'Display only the latest articles of the page which the latest articles plugin resides in.<br />Selecting \"Yes\" will disable the \"Page Targeting\" setting.'),
(NULL, 2, 3, 'pages_to_include', 'Pages to Include'),
(NULL, 2, 3, 'pages_to_include_descr', 'Enter the ID\'s of the pages you want to select articles from, separate values with comma. Leave empty to select articles from all pages.'),
(NULL, 2, 3, 'sorting', 'Sorting'),
(NULL, 2, 3, 'sorting_descr', 'How would you like your latest articles to be sorted?'),
(NULL, 2, 3, 'title_in_bold', 'Title in Bold'),
(NULL, 2, 3, 'title_in_bold_descr', 'Display the article\'s title in bold?'),
(NULL, 2, 3, 'title_link', 'Title Link'),
(NULL, 2, 3, 'title_link_descr', 'Would you like the article\'s title to link to the full article? '),
(NULL, 2, 6, 'contact_form_paragraph', 'Contact Form Paragraph'),
(NULL, 2, 6, 'contact_form_paragraph_descr', 'This paragraph will appear right before the contact form.<br />A convenient location for your address and phone number.'),
(NULL, 2, 6, 'contact_form_settings', 'Contact Form Settings'),
(NULL, 2, 6, 'email_address', 'Email Address'),
(NULL, 2, 6, 'email_address_descr', 'Enter the email address where the submitted contact forms should be sent to:<br />Separate multiple addresses with commas.'),
(NULL, 2, 10, 'display_admin_link', 'Display Admin Link'),
(NULL, 2, 10, 'display_admin_link_descr', 'Display a link to the admin panel in the login panel for those with admin access?'),
(NULL, 2, 10, 'display_forgot_password_link', 'Display Forgot Password Link'),
(NULL, 2, 10, 'display_forgot_password_link_descr', 'Display a link to the forgot password page in the login panel?'),
(NULL, 2, 10, 'display_profile_link', 'Display Profile Link'),
(NULL, 2, 10, 'display_profile_link_descr', 'Display a link to the user\'s profile page? '),
(NULL, 2, 10, 'display_register_link', 'Display Registration Link'),
(NULL, 2, 10, 'display_register_link_descr', 'Display a link to the registration page in the login panel?'),
(NULL, 2, 10, 'user_login_panel_settings', 'User Login Panel Settings'),
(NULL, 2, 12, 'banned_emails', 'Banned Email Addresses'),
(NULL, 2, 12, 'banned_emails_descr', 'Enter a list of banned email addresses (separated by spaces):<br />To ban a specific address enter \"email@domain.com\", to ban an entire domain enter \"@domain.com\" '),
(NULL, 2, 12, 'max_username_length', 'Maximum Username Length'),
(NULL, 2, 12, 'max_username_length_descr', 'Enter the maximum username length:'),
(NULL, 2, 12, 'require_email_activation', 'Require Email Activation'),
(NULL, 2, 12, 'require_email_activation_descr', 'Require new users to validate their email address when registering: '),
(NULL, 2, 12, 'user_registration_settings', 'User Registration Settings'),
(NULL, 2, 17, 'add_image', 'Add Image'),
(NULL, 2, 17, 'add_new_section', 'Add New Section'),
(NULL, 2, 17, 'add_new_section_descr', 'You can organize your images into many directories by creating new sections:<br />(the default section is root and it can not be deleted)'),
(NULL, 2, 17, 'allow_root_upload', 'Allow Root Section Upload'),
(NULL, 2, 17, 'allow_root_upload_descr', 'Allow user uploads to the root section?'),
(NULL, 2, 17, 'allowed_image_types', 'Allowed Image Types'),
(NULL, 2, 17, 'allowed_image_types_descr', 'List of allowed image types for upload (comma separated).<br />Example: gif, jpg, jpeg, png'),
(NULL, 2, 17, 'alpha_az', 'Alphabetically A-Z'),
(NULL, 2, 17, 'alpha_za', 'Alphabetically Z-A'),
(NULL, 2, 17, 'author', 'Author'),
(NULL, 2, 17, 'author_name_az', 'Author Name A-Z'),
(NULL, 2, 17, 'author_name_za', 'Author Name Z-A'),
(NULL, 2, 17, 'auto_approve_images', 'Auto Approve Images'),
(NULL, 2, 17, 'auto_approve_images_descr', 'Automatically approve user submitted images?'),
(NULL, 2, 17, 'auto_create_thumbs', 'Auto Create Thumbnails'),
(NULL, 2, 17, 'auto_create_thumbs_descr', 'Automatically create thumbnails?'),
(NULL, 2, 17, 'center_images', 'Center Images'),
(NULL, 2, 17, 'center_images_descr', 'Would you like to center the images on the page?'),
(NULL, 2, 17, 'confirm_delete_image', 'Delete this image?'),
(NULL, 2, 17, 'confirm_regenerate_thumb', 'Regenerate the thumbnail for this image?'),
(NULL, 2, 17, 'create_midsize_images', 'Create MidSize Images'),
(NULL, 2, 17, 'create_midsize_images_descr', 'Automatically create mid-size images?<br />This allows you to show a nice medium sized image that will fit your website.'),
(NULL, 2, 17, 'create_section', 'Create Section'),
(NULL, 2, 17, 'delete', 'Delete'),
(NULL, 2, 17, 'delete_image', 'Delete Image:'),
(NULL, 2, 17, 'delete_images_in_section', 'Delete all images in this Section?'),
(NULL, 2, 17, 'delete_section', 'Delete this Section?'),
(NULL, 2, 17, 'description', 'Description:'),
(NULL, 2, 17, 'display_author_name', 'Display Author Name'),
(NULL, 2, 17, 'display_author_name_descr', 'Display the author\'s name near each image?'),
(NULL, 2, 17, 'display_section_image_count', 'Display Section Image Count'),
(NULL, 2, 17, 'display_section_image_count_descr', 'Display the image count in each section?'),
(NULL, 2, 17, 'display_section_online', 'Active: Display this Section online?'),
(NULL, 2, 17, 'display_view_count', 'Display View Count'),
(NULL, 2, 17, 'display_view_count_descr', 'Display the number of times the image has been viewed?'),
(NULL, 2, 17, 'do_not_move', 'Don\'t Move'),
(NULL, 2, 17, 'edit_image', 'Edit Image'),
(NULL, 2, 17, 'edit_section', 'Edit Section'),
(NULL, 2, 17, 'edit_section_descr', 'Change the settings and images of this section:'),
(NULL, 2, 17, 'enable_comments', 'Enable Comments'),
(NULL, 2, 17, 'enable_comments_descr', 'Enable comments in the Image Gallery?'),
(NULL, 2, 17, 'enable_image_resizing_required', 'Please enable Image Resizing under settings first.'),
(NULL, 2, 17, 'errors_found', 'Errors Found:'),
(NULL, 2, 17, 'folder_not_found', 'folder not found, please create it.'),
(NULL, 2, 17, 'folder_not_writable', 'folder not writable, please CHMOD to 0777.'),
(NULL, 2, 17, 'gd_disabled', 'GD image library is required for importing multiple images, contact your server admin.'),
(NULL, 2, 17, 'image', 'Image:'),
(NULL, 2, 17, 'image_author_required', 'Image Author Required'),
(NULL, 2, 17, 'image_author_required_descr', 'Is the image author required for image uploads?'),
(NULL, 2, 17, 'image_description_required', 'Image Description Required'),
(NULL, 2, 17, 'image_description_required_descr', 'Is the image description required for image uploads?'),
(NULL, 2, 17, 'image_display_mode', 'Image Display Mode'),
(NULL, 2, 17, 'image_display_mode_descr', 'Mode for displaying a single image?'),
(NULL, 2, 17, 'image_gallery_settings', 'Image Gallery Settings'),
(NULL, 2, 17, 'image_imported', 'Successfully re-sized and imported.'),
(NULL, 2, 17, 'image_not_imported', 'image was not imported.'),
(NULL, 2, 17, 'image_notification', 'Image Notification'),
(NULL, 2, 17, 'image_notification_descr', 'This email address will receive an email message when a new image is submitted:<br />Separate multiple addresses with commas.'),
(NULL, 2, 17, 'image_section_deleted', 'Image Section Deleted'),
(NULL, 2, 17, 'image_title_required', 'Image Title Required'),
(NULL, 2, 17, 'image_title_required_descr', 'Is the image title required for image uploads?'),
(NULL, 2, 17, 'images', 'Images'),
(NULL, 2, 17, 'images_per_page', 'Number of Images per Page'),
(NULL, 2, 17, 'images_per_page_descr', 'Enter the number of images that a section should display per page:'),
(NULL, 2, 17, 'images_per_row', 'Number of Images per Row'),
(NULL, 2, 17, 'images_per_row_descr', 'Enter the number of images to be displayed per row:'),
(NULL, 2, 17, 'import_image_author', 'Author of images:'),
(NULL, 2, 17, 'import_image_count', 'Number of Images to Import from folder:'),
(NULL, 2, 17, 'import_image_location', 'Section to import images into:'),
(NULL, 2, 17, 'import_images', 'Import Images'),
(NULL, 2, 17, 'import_images_from', 'Import Images From:'),
(NULL, 2, 17, 'import_location_not_found', 'Specified import folder not found.'),
(NULL, 2, 17, 'import_results', 'Batch Image Import Results'),
(NULL, 2, 17, 'imported_count', 'Number of images imported:'),
(NULL, 2, 17, 'keep_images_descr', 'Keep Images: Keep full size images? (see mid size options under settings)'),
(NULL, 2, 17, 'max_midsize_height', 'Max Mid-Size Height'),
(NULL, 2, 17, 'max_midsize_height_descr', 'Enter the max height that the mid-size image should be re-sized to:'),
(NULL, 2, 17, 'max_midsize_width', 'Max Mid-Size Width'),
(NULL, 2, 17, 'max_midsize_width_descr', 'Enter the max width that the mid-size image should be re-sized to:'),
(NULL, 2, 17, 'max_thumb_height', 'Max Thumbnail Height'),
(NULL, 2, 17, 'max_thumb_height_descr', 'Enter the max height that a thumbnail should be re-sized to:'),
(NULL, 2, 17, 'max_thumb_width', 'Max Thumbnail Width'),
(NULL, 2, 17, 'max_thumb_width_descr', 'Enter the max width that a thumbnail should be re-sized to:'),
(NULL, 2, 17, 'max_upload_size', 'Max Upload Size'),
(NULL, 2, 17, 'max_upload_size_descr', 'Maximum image file-size for user uploads in bytes:<br />Default is 1048576 (1MB)'),
(NULL, 2, 17, 'midsize_settings', 'Mid-Size Settings'),
(NULL, 2, 17, 'move', 'Move'),
(NULL, 2, 17, 'move_images', 'Move Images to:'),
(NULL, 2, 17, 'move_imported_images_descr', 'Move Imported Images: Move all valid Images? Otherwise Images are just copied and original Images stay.'),
(NULL, 2, 17, 'newest_first', 'Newest First'),
(NULL, 2, 17, 'no_images_found', 'No images found.'),
(NULL, 2, 17, 'no_parent_for_root', 'Root section can not have a parent.'),
(NULL, 2, 17, 'no_thumb_found', 'No valid thumbnail image found, probably caused by a failed upload or thumbnail creation error.'),
(NULL, 2, 17, 'offline', 'Offline'),
(NULL, 2, 17, 'oldest_first', 'Oldest First'),
(NULL, 2, 17, 'online', 'Online'),
(NULL, 2, 17, 'options', 'Options:'),
(NULL, 2, 17, 'organize_images', 'Organize Images'),
(NULL, 2, 17, 'parent_section', 'Parent Section:'),
(NULL, 2, 17, 'php_max_upload_size', 'Allowed file size in PHP to submit is:'),
(NULL, 2, 17, 'preview', 'Preview'),
(NULL, 2, 17, 'publish_descr', 'Publish: Are you ready to publish this image on your site?'),
(NULL, 2, 17, 'regenerate_thumb', 'Regenerate Thumbnail:'),
(NULL, 2, 17, 'return_to_image_gallery', 'Return to the Image Gallery'),
(NULL, 2, 17, 'save_fullsize_images', 'Save Full-Size Images'),
(NULL, 2, 17, 'save_fullsize_images_descr', 'If you have \"Create Mid-Size Image\" enabled, then you need decide if you want to save the full-size images. If you select \"No\", then the original full-sized images will be deleted.'),
(NULL, 2, 17, 'section', 'Section'),
(NULL, 2, 17, 'section_created', 'Section Created'),
(NULL, 2, 17, 'section_image', 'Section Image:'),
(NULL, 2, 17, 'section_images_per_row', 'Number of Section Images per Row'),
(NULL, 2, 17, 'section_images_per_row_descr', 'If your sections are being displayed as images, then select how many should be shown per row:'),
(NULL, 2, 17, 'section_sort_order', 'Section Sort Order'),
(NULL, 2, 17, 'section_sort_order_descr', 'Select how you would like your sections sorted by:'),
(NULL, 2, 17, 'sort_images_by', 'Sort Images by:'),
(NULL, 2, 17, 'square_off_midsize', 'Square off Mid-Sized Images'),
(NULL, 2, 17, 'square_off_midsize_descr', 'When automatically creating mid-sized images, should the image be cropped so that it is square?'),
(NULL, 2, 17, 'square_off_thumbs', 'Square off Thumbnails'),
(NULL, 2, 17, 'square_off_thumbs_descr', 'When automatically creating thumbnails, should the image be cropped so that it is square?'),
(NULL, 2, 17, 'status', 'Status'),
(NULL, 2, 17, 'thumb_created_automatically', 'Thumbnail will be created automatically.'),
(NULL, 2, 17, 'thumb_error_image_not_imported', 'thumbnail creation failed, image not imported.'),
(NULL, 2, 17, 'thumbnail', 'Thumbnail:'),
(NULL, 2, 17, 'thumbnail_settings', 'Thumbnail Settings'),
(NULL, 2, 17, 'title', 'Title:'),
(NULL, 2, 17, 'update_image', 'Update Image'),
(NULL, 2, 17, 'update_images', 'Update Images'),
(NULL, 2, 17, 'update_section', 'Update Section'),
(NULL, 2, 17, 'upload_image_again', 'Since the original image does not exist it is suggested to delete this image and upload it again.'),
(NULL, 2, 17, 'upload_settings', 'Upload Settings'),
(NULL, 2, 17, 'use_regenerate_option', 'Since the original image still exists, use the above \"regenerate\" option to create a valid thumbnail image(s).'),
(NULL, 2, 17, 'view_image', 'View Image'),
(NULL, 2, 17, 'view_images', 'View Images'),
(NULL, 2, 17, 'view_settings', 'View Settings')");

?>